# Update all SUBSCRIBER_ACCOUNT.SUBSCRIBER_STATUS from ACTIVE to VERIFIED
update SUBSCRIBER_ACCOUNT set SUBSCRIBER_STATUS = 'VERIFIED' where SUBSCRIBER_STATUS = 'ACTIVE';

# Adding number of confirmation emails sent to an account
ALTER TABLE `SUBSCRIPTION` ADD `NUM_CONFIRM_SENT` INT NOT NULL AFTER `UNSUBSCRIBE_KEY`;

# Adding the Subscriber ID column in TRIGGER_EMAIL_ACTIVITY for Subscriber Timeline
ALTER TABLE `TRIGGER_EMAIL_ACTIVITY` ADD `SUBSCRIBER_ID` BIGINT NOT NULL AFTER `SUBCRIBER_EMAIL`;
# To correct a spelling mistake
ALTER TABLE `TRIGGER_EMAIL_ACTIVITY` CHANGE `SUBCRIBER_EMAIL` `SUBSCRIBER_EMAIL` varchar(255);
# Migrate all Subscriber ID into TRIGGER_EMAIL_ACTIVITY
UPDATE 
`TRIGGER_EMAIL_ACTIVITY` t 
LEFT JOIN ASSIGN_CAMPAIGN_ACTIVITY aca ON t.TRIGGERING_OBJECT = aca.TARGET
LEFT JOIN ASSIGN_CAMPAIGN_CLIENT acc ON aca.SOURCE = acc.SOURCE
LEFT JOIN SUBSCRIBER_ACCOUNT sa ON sa.EMAIL = t.SUBSCRIBER_EMAIL
LEFT JOIN SUBSCRIBER_OWNERSHIP so ON so.SOURCE = sa.OBJECTID AND so.TARGET = acc.TARGET
SET t.SUBSCRIBER_ID = so.SOURCE

# Adding SubscriberCount table
CREATE TABLE `SUBSCRIBER_COUNT` (
  `START_DATE` date NOT NULL,
  `SNO` int(11) NOT NULL,
  `END_DATE` date NOT NULL,
  `DATA_TYPE` varchar(255) NOT NULL,
  `CHANGED_BY` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `DATE_CHANGED` date DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  `version` bigint(20) NOT NULL,
  `OWNER` bigint(20) NOT NULL,
  PRIMARY KEY (`START_DATE`,`SNO`,`OWNER`,`END_DATE`,`DATA_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SUBSCRIBER_COUNT_MAP` (
  `START_DATE` date NOT NULL,
  `SNO` int(11) NOT NULL,
  `OWNER` bigint(20) NOT NULL,
  `END_DATE` date NOT NULL,
  `DATA_TYPE` varchar(255) NOT NULL,
  `COUNT` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL,
  PRIMARY KEY (`START_DATE`,`SNO`,`OWNER`,`END_DATE`,`DATA_TYPE`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
