# Update all SUBSCRIBER_ACCOUNT.SUBSCRIBER_STATUS from ACTIVE to VERIFIED
update SUBSCRIBER_ACCOUNT set SUBSCRIBER_STATUS = 'VERIFIED' where SUBSCRIBER_STATUS = 'ACTIVE';

# Adding number of confirmation emails sent to an account
ALTER TABLE `SUBSCRIPTION` ADD `NUM_CONFIRM_SENT` INT NOT NULL AFTER `UNSUBSCRIBE_KEY`;

# Adding the Subscriber ID column in TRIGGER_EMAIL_ACTIVITY for Subscriber Timeline
ALTER TABLE `TRIGGER_EMAIL_ACTIVITY` ADD `SUBSCRIBER_ID` BIGINT NOT NULL AFTER `SUBCRIBER_EMAIL`;
# To correct a spelling mistake
ALTER TABLE `TRIGGER_EMAIL_ACTIVITY` CHANGE `SUBCRIBER_EMAIL` `SUBSCRIBER_EMAIL` varchar(255);
# Migrate all Subscriber ID into TRIGGER_EMAIL_ACTIVITY
UPDATE 
`TRIGGER_EMAIL_ACTIVITY` t 
LEFT JOIN ASSIGN_CAMPAIGN_ACTIVITY aca ON t.TRIGGERING_OBJECT = aca.TARGET
LEFT JOIN ASSIGN_CAMPAIGN_CLIENT acc ON aca.SOURCE = acc.SOURCE
LEFT JOIN SUBSCRIBER_ACCOUNT sa ON sa.EMAIL = t.SUBSCRIBER_EMAIL
LEFT JOIN SUBSCRIBER_OWNERSHIP so ON so.SOURCE = sa.OBJECTID AND so.TARGET = acc.TARGET
SET t.SUBSCRIBER_ID = so.SOURCE
