DELETE u FROM USER u INNER JOIN USERTYPE ut on ut.OBJECTID=u.USERTYPE_OBJECTID  WHERE ut.USERTYPENAME='expectedUserType';
 DELETE ut FROM USERTYPE ut   WHERE ut.USERTYPENAME='expectedUserType';;
DELETE ua FROM USERACCOUNT ua  WHERE ua.USERNAME='expectedUserName';